### ISSUE TITLE
Traducir ley bardolini

### ISSUE THREAD

**Issue by jorgebg** [premiosbrandolini/premiosbrandolini.github.io#1]

**Comment by Khram** [comment]
Sólo es traducirla? Fácil:

Principio de asimetria de las chorradas/memeces/tonterías/bobadas/gilipolleces (podría poner mierda, pero meh)

La cantidad de energía necesaria para refutar una chorrada/memez/tontería/bobada/gilipollez
es un orden de magnitud superior a la necesaria para producirla.

¿Comentarios? ¿Qué palabra elegimos?

**Comment by Nigridal** [comment]
"Requiere un orden de magnitud de esfuerzo menos crear una gilipollez que demostrar que es falsa" creo que sería un enunciamiento más eficiente

**Comment by Khram** [comment]
Pero le quita ese tono científico...

**Comment by jorgebg** [comment]
Me gusta más la de @Khram. Eligiría _tontería_ o _memez_

**Comment by metaltrooper** [comment]
Memez. Palabra a la par divertida y rotunda

**Comment by jorgebg** [comment]
Va quedando así entonces

> La cantidad de energía necesaria para refutar una memez es un orden de magnitud superior a la necesaria para producirla.

**Comment by VaryIngweion** [comment]
La primera "necesaria" la cambiaría por "requerida". «La cantidad de energía requerida para refutar una memez es de un orden de magnitud superior a la necesaria para producirla»

O incluso "el requerimiento de energía"

**Comment by jorgebg** [comment]
Actualizado entonces :+1: si tenéis alguna pega, reabrir el hilo o gritar en twitter
