### ISSUE TITLE
Crear blog corporativo

### ISSUE THREAD

**Issue by jorgebg** [premiosbrandolini/premiosbrandolini.github.io#3]
Resumen:
- Los Premios Brandolini son otorgados por Borregos Illuminati.
- Borregos Illuminati es un blog https://borregosilluminati.wordpress.com, donde todos podemos escribir artículos y lo mantiene @vtsartas 
- Los certamen Premios Brandolini son una web: http://premiosbrandolini.github.io, donde se publican las encuestas y se enlazan desde el blog. Mantenido por @jorgebg

**Comment by Khram** [comment]
La idea no es mía, es de @qmph, preguntadle a él...

**Comment by metaltrooper** [comment]
Joder, esto es magia. Otra vez. Os maldigo. Y os envidio. Pero os maldigo XD

**Comment by jorgebg** [comment]
Es que aquí podemos debatir en más de 10 caracteres :v:

**Comment by jorgebg** [comment]
@Khram lo ha puesto en un tweet o algo? Le invitamos aquí sino

**Comment by Khram** [comment]
Sí, invítale. Lo ha puesto en un tuit:

https://twitter.com/qmph_es/status/609055620952657920

¿Se podría incluir en la página de los Brandolini o algo? Por centralizarlo todo en el mismo sitio...

**Comment by jorgebg** [comment]
Aquí se puede alojar un blog gratuitamente, pero con 'magia', escribiendo en markdown. En realidad es muy simple, cada entrada es un archivo de texto en markdown. Por mí no hay problema, pero los profanos como @metaltrooper igual prefieren llamar a la inquisición :laughing:

**Comment by Khram** [comment]
Eeeeeehh... ¿Qué es markdown? ¿Un procesador de texto normal?

**Comment by jorgebg** [comment]
Si escribís los artículos y no os atrevéis a usar este formato, yo me comprometo a mantenerlo, me pasáis a mí los artículos y los voy subiendo.

Si @qmph_es tiene algun servidor y no le importa alojarlo ahí eso ya es otra cosa :smile:

**Comment by Khram** [comment]
ni idea... ha mandado un tuit colectivo con una captura de un blog en WordPress... yo abogaría por tenerlo todo juntico, pero enlazarlo aquí y escribir allí, tampoco me va a dar urticaria...

**Comment by jorgebg** [comment]
@Khram Markdown es el formato en el que estás escribiendo estas mismas respuestas. Algunos ejemplos:

---

```
Hola soy **Jorge**
```

Hola soy **Jorge**

---

```
Tengo *siete* vidas:
- Una
- Dos
- Tres

...
```

Tengo _siete_ vidas:
- Una
- Dos
- Tres

...

**Comment by Khram** [comment]
Curioso...

**Comment by jorgebg** [comment]
Yo propuse esto por tener algo, esto no me costaba nada. Si @qmph_es puede hacerlo mejor, lo movemos a su server y tener todo alli centralizado, yo encantado :smile: :+1:

**Comment by Khram** [comment]
De nuevo, eso es cosa de él... invítale a ver qué se cuenta...

**Comment by jorgebg** [comment]
Por otro lado, independientemente de que hagamos un blog, ¿se os ocurre algun otro sitio para discutir ideas o os sirve éste? Porque en twitter dentro de poco vamos a tener espacio negativo para escribir jejejej

**Comment by metaltrooper** [comment]
Cabroneeeeess XD

**Comment by Khram** [comment]
Yo aquí estoy bien. Para discutir moviditas en plan foro no está mal. Pero si no, también podemos hacernos un foro. Y crear carnés. Y dar puntos por comprar gasolina y luego cambiarlos por productos limoneros...

Ya, ya paro que se me va...

**Comment by vtsartas** [comment]
Hola Hola

**Comment by jorgebg** [comment]
JAJJAAJJAJAJAJAJAJAJ

**Comment by Khram** [comment]
Empezamos ya a ser unos cuántos, eh...

**Comment by vtsartas** [comment]
Server no tengo, por eso pensé que Wordpress era buena opción ya que lo manejamos la mayoría.

**Comment by jorgebg** [comment]
@vtsartas tienes toda la razon, yo tambien me voy a lo dificil jajajaj

**Comment by Khram** [comment]
Yo lo que decía era tenerlo todo en el mismo sitio, pero si os parece mejor WP, perfecto...

**Comment by vtsartas** [comment]
La cosa sería aprovechar las cosas que surgen en los "flames" borreguiles para hacer un blog colaborativo... cada uno haría de vez en cuando un articulillo en la tónica del grupo illuminati. Podría ser una web de humor para abordar los temas limonares... igual resulta :D

**Comment by Khram** [comment]
Yo lo compro...

**Comment by jorgebg** [comment]
compro tambien, pero el mantenimiento para mi es mas dificil, de wordpress no controlo tanto :walking:

**Comment by Khram** [comment]
Será cuestión de trastear. Yo no sabía demasiado de blogspot y aquí me tienes.

**Comment by vtsartas** [comment]
Wordpress lo llevo bien, no problemo. Empezamos con la versión gratis que es más reducida para diseño gráfico (la intentaré dejar lo mejor posible) y tal... pero permite poner los artículos fácil.

**Comment by vtsartas** [comment]
Y así hacemos grupo... podríamos ser el "naukas" del futuro xDDDD

**Comment by jorgebg** [comment]
jajajajajjaja me parece bien! deberiamos pedir a los demas q al menos leyesen este hilo y confirmasen en twitter, pero yo creo q les va a dar igual una cosa q otra jejeje

**Comment by metaltrooper** [comment]
En serio: os odio y os maldigo XDD Y a mí también

**Comment by Khram** [comment]
podríamos ser el "naukas" del futuro <--- podríamos lanzarles una opa hostil y absorberlos XDDD

**Comment by jorgebg** [comment]
@Khram JAJAJAJAJJA colaboren por favor colaboren

**Comment by vtsartas** [comment]
jjjjjjjjjjjjjjjjjj
Importante: si tenéis ya usuario de wordpress.com me lo decís y os añado. Y si no, os lo hacéis :P

**Comment by Khram** [comment]
En menos de una semana me he creado usuarios en github, reddit, wordpress y pornhuNOOOOBORRABORRABORRA

**Comment by jorgebg** [comment]
JAJAJJAJAJAJAJAJAJJAJAJAJAJAJ

**Comment by jorgebg** [comment]
bienvenidos a github :heart: yo creo en ésta herramienta y ojalá empiece a utilizarse más alla de sólo en informática :smile:

**Comment by vtsartas** [comment]
jjajjajajajaja

**Comment by jorgebg** [comment]
@vtsartas el dominio de wordpress ya lo tienes?

**Comment by vtsartas** [comment]
Sí: https://borregosilluminati.wordpress.com

**Comment by jorgebg** [comment]
@vtsartas wtf borregosilluminati? por qué no premiosbrandolini?

**Comment by Khram** [comment]
Va, solof1sincirco en WordPress también...

Khram estaba pillado, me encantaría saber por quién

**Comment by vtsartas** [comment]
Los premios son algo que otorga el grupo borreguil... que es la base y dónde gira todo ;)

**Comment by metaltrooper** [comment]
Mejor BorregosIlluminaty. La "Y" del final es en homenaje a la limones y las risas que nos dió la tipa

**Comment by Khram** [comment]
Tarde...

**Comment by jorgebg** [comment]
aaamh ok

**Comment by vtsartas** [comment]
Too late... xDDD

La página de los premios se puede dejar aquí, y se pone enlace en el WP, etc.

**Comment by jorgebg** [comment]
aaaaaaaamh, pues como veais, a mi no me importa ir manteniendo una para cada certamen

**Comment by Khram** [comment]
Yo tengo puesto un enlace en el encabezado de mi blog... se puede hacer algo similar. 

Eso sí, el lunes cuando comencemos la primera semana de encuesta, habría que poner el enlace a la encuesta en la página de los premios.

**Comment by vtsartas** [comment]
Así lo diferenciamos, premios aquí y lo demás en el WP... lo dejamos así, que esta ya la tenéis en marcha.

**Comment by jorgebg** [comment]
sin problema, si decidis mantener aqui los premios yo me encargo. este finde le pego una reforma a la web para prepararla, con una pagina por certamen

**Comment by jorgebg** [comment]
y aqui se admiten las sugerencias q querais, podeis crear tareas, reportar erratas, etc

**Comment by vtsartas** [comment]
Genial. Yo trastearé con el WP a ver si el lunes podemos tener algo a la vez ;-)

**Comment by Khram** [comment]
Yo tengo ya preparada la encuesta en surveymonkey. Es sólo dar el enlace y que la gente vote. Voy metiendo los candidatos según me van llegando.

**Comment by jorgebg** [comment]
por si hay alguno muy muy emocionado: https://es.godaddy.com/domains/searchresults.aspx?domainToCheck=borregosilluminati.com

**Comment by jorgebg** [comment]
puedes poner el enlace por aquí o en una tarea aparte please?

**Comment by Khram** [comment]
Aún no está cerrada. Cuando esté cerrada, te lo paso. Hasta el domingo pueden seguir enviando candidatos...

**Comment by vtsartas** [comment]
Nada nada... paso a paso... Además la idea es pasárnoslo bien, divulgar... Ya si hace falta ya veremos alojamiento más serio ;-)

**Comment by jorgebg** [comment]
ok ok :smile:

**Comment by jorgebg** [comment]
@vtsartas me referia solo al dominio, nada de alojamiento aun :yum:

**Comment by vtsartas** [comment]
Tampoco, creo yo, vamos a ver la marcha de las primeras semanas antes :)

**Comment by metaltrooper** [comment]
Sois unas fieras ...

**Comment by jorgebg** [comment]
@metaltrooper :tiger: :tiger:

**Comment by metaltrooper** [comment]
No sé por qué no sale mi foto por aquí, si la he añadido a mi perfil público ...

**Comment by jorgebg** [comment]
@metaltrooper  A mí me sale, es tema de caché, refresca varias veces jejeje

**Comment by metaltrooper** [comment]
Vale. Voy a la ducha XDDD

**Comment by francisconz84** [comment]
Bueno pues ya ando por aquí, saludillos a tó kiski!

**Comment by vtsartas** [comment]
Saludos Francisco!

**Comment by metaltrooper** [comment]
Hola borreguito ;-)

**Comment by francisconz84** [comment]
Beee beee.. ¿aquí es lo de dominar el mundo?, a ver si nos damos algo de prisa, que los de monsanto y las malvadas farmacéuticas llevan años pagándome y todavía no me han dicho dónde está la cuenta bancaria..

**Comment by vtsartas** [comment]
Aquí serán reveladas todas las borregadas hasta ahora ocultas... ñiaaajajaa

**Comment by metaltrooper** [comment]
Es una cuenta conjunta. Ahí estamos todos XDD

**Comment by VaryIngweion** [comment]
Yo tengo wordpress seguro porque en el blog de la dinosaurios usaba wordpress. ¿Cual es? Pues ahora no recuerdo pero supongo que será VaryIngweion como siempre.

**Comment by jorgebg** [comment]
@VaryIngweion si pones el enlace de tu blog creo que podemos sacarlo

**Comment by VaryIngweion** [comment]
varyingweion

**Comment by vtsartas** [comment]
Invitación enviada Vary, tendrás que aceptarla ;)

El blog ya tiene un aspecto. Si os gusta, usamos ese theme gratis. No se puede añadir o modificar mucho de ahí, pero queda resultón: https://borregosilluminati.wordpress.com

**Comment by francisconz84** [comment]
Genial vtsartas!!! el blog está "que quita er sentío"

**Comment by vtsartas** [comment]
He dejado la votación como entrada en el blog:
https://borregosilluminati.wordpress.com/2015/06/11/1er-premio-brandolini/

**Comment by jorgebg** [comment]
Ooole que bonito!

**Comment by francisconz84** [comment]
Ya tengo cuenta wordpress, mi usuario es @francisconz84

**Comment by vtsartas** [comment]
Ya tienes la invitación a WP Francisco (la he enviado a "francisconz84", sin la "@")
A Vary se la envié y falta que la acepte ;-)

Por cierto, se entra por aquí: https://borregosilluminati.wordpress.com/wp-admin/

**Comment by francisconz84** [comment]
Muchas gracias!!

**Comment by vtsartas** [comment]
¿Hacemos un grupo cerrado de Facebook para comunicarnos con los menos técnicos? A ver si pronto pueden haber post de los borreguicos :D

**Comment by vtsartas** [comment]
A ver si os animáis a escribir algún artículo, no hace falta que sea muy largo... motivos hay con Pàmies o cosas como esta: https://youtu.be/5hWybVnSJ3o

**Comment by VaryIngweion** [comment]
Yo últimamente est´y un poco seco de ideas, pero si a alguien se le ocurre algo de algun tema que no se atreva a escribir y yo puedo controlar comentádmelo.

Vary (Á. Bayón Medrano)
soy.vary@gmail.com

http://varyingweion.blogspot.com/ http://varyingweion.blogspot.com/
http://www.flickr.com/photos/varyingweion/ http://www.flickr.com/photos/varyingweion/
http://twitter.com/#!/VaryIngweion/ http://twitter.com/#!/VaryIngweion/

Imprime este correo sólo si es completamente necesario.

**Comment by jorgebg** [comment]
Disculpad, he estado un poco liado y ahora ademas estoy de vacaciones y casi no toco el ordenador.
Acabo de actualizar los premios.

Y estoy de acuerdo con el grupo de Facebook @vtsartas, no sabía que se podía hacer eso :sweat_smile: y seguro que es mas facil para todos

**Comment by vtsartas** [comment]
Ya está creado el grupo en FB. De momento lo he dejado secreto: https://www.facebook.com/groups/BorregosIlluminati/
Quien falte que me pase su nombre/enlace en Facebook para que lo añada ;-)

**Comment by jorgebg** [comment]
Hola compañeros!

Esto no tuvo exito, voy a cerrarlo, teneis alguna objeccion? creo que tener esta web publicada solo va a traer confusion a los lectores de Borregos Illuminati :sweat_smile:
